prSections:
    - title: My Pull Requests
      filters: is:open author:@me
    - title: Needs My Review
      filters: is:open review-requested:@me
    - title: Involved
      filters: is:open involves:@me -author:@me
issuesSections:
    - title: My Issues
      filters: is:open author:@me
    - title: Assigned
      filters: is:open assignee:@me
    - title: Involved
      filters: is:open involves:@me -author:@me
repo:
    branchesRefetchIntervalSeconds: 30
    prsRefetchIntervalSeconds: 60
defaults:
    preview:
        open: true
        width: 50
    prsLimit: 20
    prApproveComment: LGTM
    issuesLimit: 20
    view: prs
    layout:
        prs:
            updatedAt:
                width: 5
            createdAt:
                width: 5
            repo:
                width: 20
            author:
                width: 15
            authorIcon:
                hidden: false
            assignees:
                width: 20
                hidden: true
            base:
                width: 15
                hidden: true
            lines:
                width: 15
        issues:
            updatedAt:
                width: 5
            createdAt:
                width: 5
            repo:
                width: 15
            creator:
                width: 10
            creatorIcon:
                hidden: false
            assignees:
                width: 20
                hidden: true
    refetchIntervalMinutes: 30
keybindings:
    prs:
        - key: o
          command: bash -c 'url=$(gh pr view {{.PrNumber}} --repo {{.RepoName}} --json url -q .url) && nvim -c "Octo $url"'
        - key: d
          command: gh pr diff {{.PrNumber}} --repo {{.RepoName}} | delta
        - key: c
          command: gh pr checkout {{.PrNumber}} --repo {{.RepoName}}
    issues:
        - key: o
          command: bash -c 'url=$(gh issue view {{.IssueNumber}} --repo {{.RepoName}} --json url -q .url) && nvim -c "Octo $url"'
repoPaths: {}
theme:
    ui:
        sectionsShowCount: true
        table:
            showSeparator: true
            compact: false
pager:
    diff: ""
confirmQuit: false
showAuthorIcons: true
smartFilteringAtLaunch: true
